import re

decor_palette = [
    0, 458752, 458753, 458754, 458756, 458836, 458837, 458758, 458760, 458762,
    458764, 458766, 458767, 458769, 458770, 458771, 458772, 458774, 458776, 458777,
    458778, 458779, 458780, 458781, 458782, 458783, 458784, 458785, 458786, 458787,
    458788, 458789, 458790, 458791, 458792, 458793, 458794, 458795, 458796, 458797,
    458798, 458799, 458800, 458802, 458804, 458805, 458806, 458807, 458812, 458814,
    458815, 458817, 458818, 458819, 458820, 458821, 458822, 458823, 458824, 458825,
    458826, 458827, 458828, 458829, 458830, 458831, 458832, 458833, 458834, 458835,
    458808, 458809, 458810, 458811, 458803, 458757, 458755, 458761, 458759, 458763,
    458765, 458768, 458775, 458801, 458816, 458813, 458773
]

with open('/home/cherry/Downloads/Robinson/decompiled/h.java', 'r') as f:
    content = f.read()

method_pattern = re.compile(
    r'public\s+final\s+void\s+(\w+)\(int\s+n2,\s+int\s+n3\)\s*\{([^}]+)\}',
    re.MULTILINE
)

methods = method_pattern.findall(content)

output_lines = []
output_lines.append("// Generated by tools/reparse_decor.py")
output_lines.append("pub struct DecorSegment {")
output_lines.append("    pub sprite_id: i32,")
output_lines.append("    pub dx: f32,")
output_lines.append("    pub dy: f32,")
output_lines.append("}")
output_lines.append("")

for name, body in methods:
    if name.islower():
        rust_name = f"DECOR_METHOD_LOWER_{name.upper()}"
    else:
        rust_name = f"DECOR_METHOD_UPPER_{name}"
        
    statements = body.strip().split(';')
    segments = []
    for stmt in statements:
        stmt = stmt.strip()
        if not stmt or 'this.a.a.a' not in stmt:
            continue
            
        p_idx_match = re.search(r'this\.a\.p\[(\d+)\]', stmt)
        raw_sprite_match = re.search(r'this\.a\.a\.a\(\s*this\.a\.a\(\),\s*(\d+),', stmt)
        
        if p_idx_match:
            p_idx = int(p_idx_match.group(1))
            sprite_id = decor_palette[p_idx]
        elif raw_sprite_match:
            sprite_id = int(raw_sprite_match.group(1))
        else:
            continue
            
        # Parse X offset
        x_part = stmt.split(',')[2].strip()
        x_offset = 0.0
        x_tail = re.search(r'this\.a\.M\s*/\s*2\s*([+-]\s*\d+)?$', x_part)
        if x_tail and x_tail.group(1):
            x_offset = float(x_tail.group(1).replace(' ', ''))
        elif not x_tail:
            tail = re.search(r'([+-]\s*\d+)\s*$', x_part)
            if tail:
                x_offset = float(tail.group(1).replace(' ', ''))
                
        # Parse Y offset
        y_part = stmt.split(',')[3].strip()
        if y_part.endswith(')'):
            y_part = y_part[:-1]
        y_offset = 0.0
        y_tail = re.search(r'this\.a\.M\s*/\s*2\s*([+-]\s*\d+)?$', y_part)
        if y_tail and y_tail.group(1):
            y_offset = float(y_tail.group(1).replace(' ', ''))
        elif not y_tail:
            tail = re.search(r'([+-]\s*\d+)\s*$', y_part)
            if tail:
                y_offset = float(tail.group(1).replace(' ', ''))
                
        segments.append((sprite_id, x_offset, y_offset))
        
    output_lines.append(f"pub const {rust_name}: &[DecorSegment] = &[")
    for sprite_id, dx, dy in segments:
        output_lines.append(f"    DecorSegment {{ sprite_id: {sprite_id}, dx: {dx}f32, dy: {dy}f32 }},")
    output_lines.append("];")
    output_lines.append("")

# Append the lookup function
lookup_fn = """pub fn get_composite_decor(did: u8, stage: u8) -> Option<&'static [DecorSegment]> {
    match did {
        18 => match stage {
            0 => Some(DECOR_METHOD_LOWER_A),
            1 => Some(DECOR_METHOD_LOWER_B),
            2 => Some(DECOR_METHOD_LOWER_C),
            3 => Some(DECOR_METHOD_LOWER_D),
            4 => Some(DECOR_METHOD_LOWER_E),
            5 => Some(DECOR_METHOD_LOWER_F),
            6 => Some(DECOR_METHOD_LOWER_G),
            7 => Some(DECOR_METHOD_LOWER_H),
            8 => Some(DECOR_METHOD_LOWER_I),
            9 => Some(DECOR_METHOD_LOWER_J),
            10 => Some(DECOR_METHOD_LOWER_K),
            11 => Some(DECOR_METHOD_LOWER_L),
            12 => Some(DECOR_METHOD_LOWER_M),
            _ => None,
        },
        1 => match stage {
            0 => Some(DECOR_METHOD_LOWER_N),
            1 => Some(DECOR_METHOD_LOWER_O),
            2 => Some(DECOR_METHOD_LOWER_P),
            3 => Some(DECOR_METHOD_LOWER_Q),
            4 => Some(DECOR_METHOD_LOWER_R),
            5 => Some(DECOR_METHOD_LOWER_S),
            6 => Some(DECOR_METHOD_LOWER_T),
            7 => Some(DECOR_METHOD_LOWER_U),
            _ => None,
        },
        5 => match stage {
            0 => Some(DECOR_METHOD_LOWER_V),
            1 => Some(DECOR_METHOD_LOWER_W),
            2 => Some(DECOR_METHOD_LOWER_X),
            3 => Some(DECOR_METHOD_LOWER_Y),
            4 => Some(DECOR_METHOD_LOWER_Z),
            5 => Some(DECOR_METHOD_UPPER_A),
            6 => Some(DECOR_METHOD_UPPER_B),
            7 => Some(DECOR_METHOD_UPPER_C),
            8 => Some(DECOR_METHOD_UPPER_D),
            _ => None,
        },
        13 => match stage {
            0 => Some(DECOR_METHOD_UPPER_E),
            1 => Some(DECOR_METHOD_UPPER_F),
            2 => Some(DECOR_METHOD_UPPER_G),
            3 => Some(DECOR_METHOD_UPPER_H),
            4 => Some(DECOR_METHOD_UPPER_I),
            5 => Some(DECOR_METHOD_UPPER_J),
            6 => Some(DECOR_METHOD_UPPER_K),
            7 => Some(DECOR_METHOD_UPPER_L),
            8 => Some(DECOR_METHOD_UPPER_M),
            9 => Some(DECOR_METHOD_UPPER_N),
            10 => Some(DECOR_METHOD_UPPER_O),
            11 => Some(DECOR_METHOD_UPPER_P),
            _ => None,
        },
        21 => match stage {
            0 => Some(DECOR_METHOD_UPPER_Q),
            1 => Some(DECOR_METHOD_UPPER_R),
            2 => Some(DECOR_METHOD_UPPER_S),
            3 => Some(DECOR_METHOD_UPPER_T),
            _ => None,
        },
        22 => match stage {
            0 => Some(DECOR_METHOD_UPPER_U),
            1 => Some(DECOR_METHOD_UPPER_V),
            2 => Some(DECOR_METHOD_UPPER_V),
            3 => Some(DECOR_METHOD_UPPER_V),
            _ => None,
        },
        49 => match stage {
            0 => Some(DECOR_METHOD_UPPER_W),
            1 => Some(DECOR_METHOD_UPPER_X),
            2 => Some(DECOR_METHOD_UPPER_Y),
            3 => Some(DECOR_METHOD_UPPER_Z),
            4 => Some(DECOR_METHOD_LOWER_AA),
            5 => Some(DECOR_METHOD_LOWER_AB),
            _ => None,
        },
        _ => None,
    }
}
"""
output_lines.append(lookup_fn)

with open('src/decor.rs', 'w') as f:
    f.write('\n'.join(output_lines))
print("Successfully regenerated src/decor.rs!")
