// Generated by tools/reparse_decor.py
pub struct DecorSegment {
    pub sprite_id: i32,
    pub dx: f32,
    pub dy: f32,
}

pub const DECOR_METHOD_LOWER_A: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 0.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: -2.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -4.0f32,
        dy: -45.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -6.0f32,
        dy: -55.0f32,
    },
    DecorSegment {
        sprite_id: 458806,
        dx: -8.0f32,
        dy: -73.0f32,
    },
];

pub const DECOR_METHOD_LOWER_B: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 2.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 3.0f32,
        dy: -19.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 4.0f32,
        dy: -27.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 6.0f32,
        dy: -37.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 6.0f32,
        dy: -46.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 9.0f32,
        dy: -52.0f32,
    },
    DecorSegment {
        sprite_id: 458805,
        dx: 10.0f32,
        dy: -65.0f32,
    },
];

pub const DECOR_METHOD_LOWER_C: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 0.0f32,
        dy: -9.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -1.0f32,
        dy: -20.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -4.0f32,
        dy: -28.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -7.0f32,
        dy: -33.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -11.0f32,
        dy: -40.0f32,
    },
    DecorSegment {
        sprite_id: 458809,
        dx: -16.0f32,
        dy: -47.0f32,
    },
];

pub const DECOR_METHOD_LOWER_D: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 0.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 0.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 1.0f32,
        dy: -47.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 1.0f32,
        dy: -61.0f32,
    },
    DecorSegment {
        sprite_id: 458806,
        dx: 0.0f32,
        dy: -80.0f32,
    },
];

pub const DECOR_METHOD_LOWER_E: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: -1.0f32,
        dy: -6.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: -3.0f32,
        dy: -17.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: -5.0f32,
        dy: -28.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: -7.0f32,
        dy: -38.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: -7.0f32,
        dy: -50.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -8.0f32,
        dy: -61.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -7.0f32,
        dy: -70.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -5.0f32,
        dy: -82.0f32,
    },
    DecorSegment {
        sprite_id: 458810,
        dx: -4.0f32,
        dy: -100.0f32,
    },
];

pub const DECOR_METHOD_LOWER_F: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 0.0f32,
        dy: -10.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 2.0f32,
        dy: -20.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 2.0f32,
        dy: -28.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 6.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 10.0f32,
        dy: -43.0f32,
    },
    DecorSegment {
        sprite_id: 458805,
        dx: 12.0f32,
        dy: -53.0f32,
    },
];

pub const DECOR_METHOD_LOWER_G: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -10.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 1.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458809,
        dx: -2.0f32,
        dy: -37.0f32,
    },
];

pub const DECOR_METHOD_LOWER_H: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 1.0f32,
        dy: -18.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 5.0f32,
        dy: -26.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 9.0f32,
        dy: -34.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 13.0f32,
        dy: -40.0f32,
    },
    DecorSegment {
        sprite_id: 458805,
        dx: 23.0f32,
        dy: -51.0f32,
    },
];

pub const DECOR_METHOD_LOWER_I: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 2.0f32,
        dy: -7.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 4.0f32,
        dy: -17.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 5.0f32,
        dy: -28.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 6.0f32,
        dy: -38.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 5.0f32,
        dy: -50.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 4.0f32,
        dy: -61.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 2.0f32,
        dy: -70.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -1.0f32,
        dy: -82.0f32,
    },
    DecorSegment {
        sprite_id: 851970,
        dx: 10.0f32,
        dy: -102.0f32,
    },
    DecorSegment {
        sprite_id: 851970,
        dx: -3.0f32,
        dy: -90.0f32,
    },
    DecorSegment {
        sprite_id: 458806,
        dx: -3.0f32,
        dy: -100.0f32,
    },
];

pub const DECOR_METHOD_LOWER_J: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458807,
        dx: -1.0f32,
        dy: -39.0f32,
    },
];

pub const DECOR_METHOD_LOWER_K: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: 1.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: 1.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458811,
        dx: 3.0f32,
        dy: -52.0f32,
    },
];

pub const DECOR_METHOD_LOWER_L: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458777,
        dx: 0.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458777,
        dx: -2.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458778,
        dx: -3.0f32,
        dy: -34.0f32,
    },
    DecorSegment {
        sprite_id: 458811,
        dx: -10.0f32,
        dy: -49.0f32,
    },
];

pub const DECOR_METHOD_LOWER_M: &[DecorSegment] = &[DecorSegment {
    sprite_id: 458807,
    dx: 0.0f32,
    dy: -16.0f32,
}];

pub const DECOR_METHOD_LOWER_N: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: -1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: -1.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: -3.0f32,
        dy: -37.0f32,
    },
    DecorSegment {
        sprite_id: 458754,
        dx: -4.0f32,
        dy: -50.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: 3.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -7.0f32,
        dy: -72.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: 8.0f32,
        dy: -58.0f32,
    },
];

pub const DECOR_METHOD_LOWER_O: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: -1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: -2.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: -1.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458754,
        dx: 3.0f32,
        dy: -1.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: -9.0f32,
        dy: -32.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 5.0f32,
        dy: -68.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -12.0f32,
        dy: -58.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: 9.0f32,
        dy: -26.0f32,
    },
];

pub const DECOR_METHOD_LOWER_P: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458802,
        dx: 2.0f32,
        dy: -78.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: 0.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458754,
        dx: -1.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: -3.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458757,
        dx: 12.0f32,
        dy: -31.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 18.0f32,
        dy: -56.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -8.0f32,
        dy: -61.0f32,
    },
];

pub const DECOR_METHOD_LOWER_Q: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: 2.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: 7.0f32,
        dy: -1.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: -4.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458757,
        dx: 5.0f32,
        dy: -36.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 6.0f32,
        dy: -62.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -12.0f32,
        dy: -40.0f32,
    },
];

pub const DECOR_METHOD_LOWER_R: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458757,
        dx: 4.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: -7.0f32,
        dy: -15.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: 6.0f32,
        dy: 0.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -4.0f32,
        dy: -65.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -10.0f32,
        dy: -43.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 9.0f32,
        dy: -49.0f32,
    },
];

pub const DECOR_METHOD_LOWER_S: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: 2.0f32,
        dy: -25.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: 3.0f32,
        dy: -37.0f32,
    },
    DecorSegment {
        sprite_id: 458754,
        dx: 3.0f32,
        dy: -50.0f32,
    },
    DecorSegment {
        sprite_id: 458756,
        dx: -8.0f32,
        dy: -2.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -12.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: 0.0f32,
        dy: -74.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 23.0f32,
        dy: -81.0f32,
    },
];

pub const DECOR_METHOD_LOWER_T: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: 0.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: -1.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458755,
        dx: -1.0f32,
        dy: -37.0f32,
    },
    DecorSegment {
        sprite_id: 458757,
        dx: -5.0f32,
        dy: 0.0f32,
    },
    DecorSegment {
        sprite_id: 458757,
        dx: 8.0f32,
        dy: -1.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -23.0f32,
        dy: -65.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 0.0f32,
        dy: -62.0f32,
    },
];

pub const DECOR_METHOD_LOWER_U: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458753,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458753,
        dx: 2.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458754,
        dx: 2.0f32,
        dy: -37.0f32,
    },
    DecorSegment {
        sprite_id: 458754,
        dx: 3.0f32,
        dy: -50.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -1.0f32,
        dy: -74.0f32,
    },
    DecorSegment {
        sprite_id: 458803,
        dx: 21.0f32,
        dy: -57.0f32,
    },
    DecorSegment {
        sprite_id: 458802,
        dx: -15.0f32,
        dy: -57.0f32,
    },
];

pub const DECOR_METHOD_LOWER_V: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 2.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 4.0f32,
        dy: -34.0f32,
    },
    DecorSegment {
        sprite_id: 458758,
        dx: 9.0f32,
        dy: -41.0f32,
    },
    DecorSegment {
        sprite_id: 458761,
        dx: 12.0f32,
        dy: -55.0f32,
    },
    DecorSegment {
        sprite_id: 458762,
        dx: 2.0f32,
        dy: -44.0f32,
    },
    DecorSegment {
        sprite_id: 458764,
        dx: 18.0f32,
        dy: -68.0f32,
    },
    DecorSegment {
        sprite_id: 458766,
        dx: -8.0f32,
        dy: -2.0f32,
    },
    DecorSegment {
        sprite_id: 458767,
        dx: 9.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 19.0f32,
        dy: -93.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -11.0f32,
        dy: -70.0f32,
    },
];

pub const DECOR_METHOD_LOWER_W: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 0.0f32,
        dy: -9.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -1.0f32,
        dy: -19.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -2.0f32,
        dy: -30.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -3.0f32,
        dy: -41.0f32,
    },
    DecorSegment {
        sprite_id: 458759,
        dx: -9.0f32,
        dy: -74.0f32,
    },
    DecorSegment {
        sprite_id: 458762,
        dx: -13.0f32,
        dy: -88.0f32,
    },
    DecorSegment {
        sprite_id: 458764,
        dx: 8.0f32,
        dy: 0.0f32,
    },
    DecorSegment {
        sprite_id: 458767,
        dx: -11.0f32,
        dy: -17.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 3.0f32,
        dy: -71.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -26.0f32,
        dy: -111.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -9.0f32,
        dy: -56.0f32,
    },
];

pub const DECOR_METHOD_LOWER_X: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 1.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458759,
        dx: -5.0f32,
        dy: -32.0f32,
    },
    DecorSegment {
        sprite_id: 458761,
        dx: -11.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458762,
        dx: -9.0f32,
        dy: -48.0f32,
    },
    DecorSegment {
        sprite_id: 458764,
        dx: 4.0f32,
        dy: -34.0f32,
    },
    DecorSegment {
        sprite_id: 458766,
        dx: -22.0f32,
        dy: -61.0f32,
    },
    DecorSegment {
        sprite_id: 458767,
        dx: 10.0f32,
        dy: -2.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 11.0f32,
        dy: -59.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -6.0f32,
        dy: -39.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -26.0f32,
        dy: -88.0f32,
    },
];

pub const DECOR_METHOD_LOWER_Y: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 2.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 4.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 6.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 8.0f32,
        dy: -46.0f32,
    },
    DecorSegment {
        sprite_id: 458759,
        dx: -9.0f32,
        dy: -66.0f32,
    },
    DecorSegment {
        sprite_id: 458763,
        dx: 5.0f32,
        dy: -1.0f32,
    },
    DecorSegment {
        sprite_id: 458765,
        dx: -4.0f32,
        dy: -7.0f32,
    },
    DecorSegment {
        sprite_id: 458768,
        dx: 9.0f32,
        dy: -102.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 6.0f32,
        dy: -93.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 21.0f32,
        dy: -75.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 2.0f32,
        dy: -59.0f32,
    },
];

pub const DECOR_METHOD_LOWER_Z: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 2.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 4.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 3.0f32,
        dy: -47.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 1.0f32,
        dy: -56.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -3.0f32,
        dy: -68.0f32,
    },
    DecorSegment {
        sprite_id: 458758,
        dx: 0.0f32,
        dy: -76.0f32,
    },
    DecorSegment {
        sprite_id: 458760,
        dx: 13.0f32,
        dy: -7.0f32,
    },
    DecorSegment {
        sprite_id: 458763,
        dx: 8.0f32,
        dy: -53.0f32,
    },
    DecorSegment {
        sprite_id: 458765,
        dx: -6.0f32,
        dy: -6.0f32,
    },
    DecorSegment {
        sprite_id: 458766,
        dx: -17.0f32,
        dy: -80.0f32,
    },
    DecorSegment {
        sprite_id: 458767,
        dx: 18.0f32,
        dy: -67.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 1.0f32,
        dy: -38.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -11.0f32,
        dy: -70.0f32,
    },
];

pub const DECOR_METHOD_UPPER_A: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 1.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 2.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458761,
        dx: -10.0f32,
        dy: -18.0f32,
    },
    DecorSegment {
        sprite_id: 458764,
        dx: 6.0f32,
        dy: -31.0f32,
    },
    DecorSegment {
        sprite_id: 458766,
        dx: 8.0f32,
        dy: -2.0f32,
    },
];

pub const DECOR_METHOD_UPPER_B: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: -1.0f32,
        dy: -9.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -3.0f32,
        dy: -20.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -4.0f32,
        dy: -31.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -5.0f32,
        dy: -42.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: -7.0f32,
        dy: -53.0f32,
    },
    DecorSegment {
        sprite_id: 458767,
        dx: 6.0f32,
        dy: -16.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -13.0f32,
        dy: -71.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 2.0f32,
        dy: -59.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -15.0f32,
        dy: -25.0f32,
    },
];

pub const DECOR_METHOD_UPPER_C: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458837,
        dx: 2.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458837,
        dx: 4.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458758,
        dx: 10.0f32,
        dy: -31.0f32,
    },
    DecorSegment {
        sprite_id: 458761,
        dx: -9.0f32,
        dy: -6.0f32,
    },
    DecorSegment {
        sprite_id: 458765,
        dx: 0.0f32,
        dy: -30.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 7.0f32,
        dy: -72.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: -7.0f32,
        dy: -62.0f32,
    },
    DecorSegment {
        sprite_id: 458798,
        dx: 14.0f32,
        dy: -53.0f32,
    },
];

pub const DECOR_METHOD_UPPER_D: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458758,
        dx: 5.0f32,
        dy: -7.0f32,
    },
    DecorSegment {
        sprite_id: 458764,
        dx: 8.0f32,
        dy: -15.0f32,
    },
];

pub const DECOR_METHOD_UPPER_E: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 0.0f32,
        dy: -36.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 0.0f32,
        dy: -48.0f32,
    },
    DecorSegment {
        sprite_id: 458772,
        dx: -10.0f32,
        dy: -25.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: 9.0f32,
        dy: -17.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -4.0f32,
        dy: -85.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: 4.0f32,
        dy: -62.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -13.0f32,
        dy: -50.0f32,
    },
];

pub const DECOR_METHOD_UPPER_F: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: -1.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: -2.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -5.0f32,
        dy: -33.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -8.0f32,
        dy: -44.0f32,
    },
    DecorSegment {
        sprite_id: 458772,
        dx: -8.0f32,
        dy: -73.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: 4.0f32,
        dy: -58.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -15.0f32,
        dy: -61.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: 7.0f32,
        dy: -47.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -5.0f32,
        dy: -1.0f32,
    },
];

pub const DECOR_METHOD_UPPER_G: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: -2.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458772,
        dx: -12.0f32,
        dy: -8.0f32,
    },
    DecorSegment {
        sprite_id: 458775,
        dx: 4.0f32,
        dy: -32.0f32,
    },
];

pub const DECOR_METHOD_UPPER_H: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: 1.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 2.0f32,
        dy: -35.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 5.0f32,
        dy: -47.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 8.0f32,
        dy: -67.0f32,
    },
    DecorSegment {
        sprite_id: 458773,
        dx: 12.0f32,
        dy: -25.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: -11.0f32,
        dy: -3.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: 3.0f32,
        dy: -72.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: 19.0f32,
        dy: -57.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -6.0f32,
        dy: -47.0f32,
    },
];

pub const DECOR_METHOD_UPPER_I: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 2.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: 4.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 6.0f32,
        dy: -33.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 8.0f32,
        dy: -44.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 7.0f32,
        dy: -55.0f32,
    },
    DecorSegment {
        sprite_id: 458773,
        dx: 21.0f32,
        dy: -46.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: 5.0f32,
        dy: -87.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: 1.0f32,
        dy: -73.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -6.0f32,
        dy: -53.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: 11.0f32,
        dy: -30.0f32,
    },
];

pub const DECOR_METHOD_UPPER_J: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: -4.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -8.0f32,
        dy: -32.0f32,
    },
    DecorSegment {
        sprite_id: 458772,
        dx: 7.0f32,
        dy: -19.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: -2.0f32,
        dy: -40.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -8.0f32,
        dy: -74.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -3.0f32,
        dy: -63.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -18.0f32,
        dy: -47.0f32,
    },
];

pub const DECOR_METHOD_UPPER_K: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458771,
        dx: 0.0f32,
        dy: -11.0f32,
    },
    DecorSegment {
        sprite_id: 458772,
        dx: -13.0f32,
        dy: -4.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: 9.0f32,
        dy: -18.0f32,
    },
];

pub const DECOR_METHOD_UPPER_L: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 1.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: 2.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -2.0f32,
        dy: -36.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -4.0f32,
        dy: -47.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 8.0f32,
        dy: -34.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: 17.0f32,
        dy: -42.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -28.0f32,
        dy: -78.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -10.0f32,
        dy: -62.0f32,
    },
    DecorSegment {
        sprite_id: 458797,
        dx: -12.0f32,
        dy: -27.0f32,
    },
];

pub const DECOR_METHOD_UPPER_M: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 0.0f32,
        dy: -22.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -10.0f32,
        dy: -65.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -5.0f32,
        dy: -40.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 10.0f32,
        dy: -52.0f32,
    },
];

pub const DECOR_METHOD_UPPER_N: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: -1.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -3.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -8.0f32,
        dy: -37.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 1.0f32,
        dy: -63.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -16.0f32,
        dy: -53.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 5.0f32,
        dy: -37.0f32,
    },
];

pub const DECOR_METHOD_UPPER_O: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: -1.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: -9.0f32,
        dy: -23.0f32,
    },
    DecorSegment {
        sprite_id: 458773,
        dx: 10.0f32,
        dy: 1.0f32,
    },
    DecorSegment {
        sprite_id: 458775,
        dx: -11.0f32,
        dy: -9.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -3.0f32,
        dy: -50.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 10.0f32,
        dy: -19.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -19.0f32,
        dy: -39.0f32,
    },
];

pub const DECOR_METHOD_UPPER_P: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458770,
        dx: 0.0f32,
        dy: -24.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 0.0f32,
        dy: -36.0f32,
    },
    DecorSegment {
        sprite_id: 458771,
        dx: 1.0f32,
        dy: -78.0f32,
    },
    DecorSegment {
        sprite_id: 458773,
        dx: 25.0f32,
        dy: -53.0f32,
    },
    DecorSegment {
        sprite_id: 458774,
        dx: 11.0f32,
        dy: -16.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 22.0f32,
        dy: -74.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 4.0f32,
        dy: -60.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: 17.0f32,
        dy: -38.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -9.0f32,
        dy: -51.0f32,
    },
    DecorSegment {
        sprite_id: 458799,
        dx: -5.0f32,
        dy: -96.0f32,
    },
];

pub const DECOR_METHOD_UPPER_Q: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458781,
        dx: 2.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458782,
        dx: 3.0f32,
        dy: -45.0f32,
    },
    DecorSegment {
        sprite_id: 458783,
        dx: 4.0f32,
        dy: -61.0f32,
    },
    DecorSegment {
        sprite_id: 458783,
        dx: 0.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 9.0f32,
        dy: -87.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: -2.0f32,
        dy: -81.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 18.0f32,
        dy: -62.0f32,
    },
];

pub const DECOR_METHOD_UPPER_R: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458782,
        dx: -2.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458783,
        dx: -2.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: -8.0f32,
        dy: -51.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 6.0f32,
        dy: -40.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 11.0f32,
        dy: -30.0f32,
    },
];

pub const DECOR_METHOD_UPPER_S: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458783,
        dx: 0.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458782,
        dx: 8.0f32,
        dy: -58.0f32,
    },
    DecorSegment {
        sprite_id: 458784,
        dx: 7.0f32,
        dy: -42.0f32,
    },
    DecorSegment {
        sprite_id: 458784,
        dx: 3.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458801,
        dx: 26.0f32,
        dy: -55.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 3.0f32,
        dy: -82.0f32,
    },
];

pub const DECOR_METHOD_UPPER_T: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458782,
        dx: 1.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458784,
        dx: 4.0f32,
        dy: -43.0f32,
    },
    DecorSegment {
        sprite_id: 458801,
        dx: 6.0f32,
        dy: -75.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 0.0f32,
        dy: -65.0f32,
    },
    DecorSegment {
        sprite_id: 458783,
        dx: 3.0f32,
        dy: -28.0f32,
    },
];

pub const DECOR_METHOD_UPPER_U: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458781,
        dx: 2.0f32,
        dy: -28.0f32,
    },
    DecorSegment {
        sprite_id: 458782,
        dx: 0.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458783,
        dx: 3.0f32,
        dy: -44.0f32,
    },
    DecorSegment {
        sprite_id: 458784,
        dx: 4.0f32,
        dy: -60.0f32,
    },
    DecorSegment {
        sprite_id: 458785,
        dx: 4.0f32,
        dy: -76.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 2.0f32,
        dy: -96.0f32,
    },
    DecorSegment {
        sprite_id: 458801,
        dx: 15.0f32,
        dy: -82.0f32,
    },
    DecorSegment {
        sprite_id: 458801,
        dx: -4.0f32,
        dy: -77.0f32,
    },
];

pub const DECOR_METHOD_UPPER_V: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458782,
        dx: 9.0f32,
        dy: -58.0f32,
    },
    DecorSegment {
        sprite_id: 458783,
        dx: 1.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458784,
        dx: 5.0f32,
        dy: -27.0f32,
    },
    DecorSegment {
        sprite_id: 458785,
        dx: 7.0f32,
        dy: -42.0f32,
    },
    DecorSegment {
        sprite_id: 458800,
        dx: 15.0f32,
        dy: -81.0f32,
    },
    DecorSegment {
        sprite_id: 458801,
        dx: 26.0f32,
        dy: -51.0f32,
    },
];

pub const DECOR_METHOD_UPPER_W: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458812,
        dx: -2.0f32,
        dy: -62.0f32,
    },
    DecorSegment {
        sprite_id: 458815,
        dx: 0.0f32,
        dy: -14.0f32,
    },
    DecorSegment {
        sprite_id: 458816,
        dx: 16.0f32,
        dy: -31.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 0.0f32,
        dy: -30.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: -13.0f32,
        dy: -34.0f32,
    },
];

pub const DECOR_METHOD_UPPER_X: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458815,
        dx: -21.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458816,
        dx: 14.0f32,
        dy: -71.0f32,
    },
    DecorSegment {
        sprite_id: 458815,
        dx: 9.0f32,
        dy: -25.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 0.0f32,
        dy: -14.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 0.0f32,
        dy: -30.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: -23.0f32,
        dy: -70.0f32,
    },
    DecorSegment {
        sprite_id: 458813,
        dx: 0.0f32,
        dy: -81.0f32,
    },
    DecorSegment {
        sprite_id: 458812,
        dx: -15.0f32,
        dy: -60.0f32,
    },
    DecorSegment {
        sprite_id: 458812,
        dx: 15.0f32,
        dy: -55.0f32,
    },
];

pub const DECOR_METHOD_UPPER_Y: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458816,
        dx: 6.0f32,
        dy: -12.0f32,
    },
    DecorSegment {
        sprite_id: 458815,
        dx: -17.0f32,
        dy: -15.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 0.0f32,
        dy: -14.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 28.0f32,
        dy: -54.0f32,
    },
    DecorSegment {
        sprite_id: 458813,
        dx: -14.0f32,
        dy: -47.0f32,
    },
    DecorSegment {
        sprite_id: 458812,
        dx: 7.0f32,
        dy: -73.0f32,
    },
    DecorSegment {
        sprite_id: 458812,
        dx: 4.0f32,
        dy: -44.0f32,
    },
];

pub const DECOR_METHOD_UPPER_Z: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458812,
        dx: -2.0f32,
        dy: -30.0f32,
    },
    DecorSegment {
        sprite_id: 458815,
        dx: -9.0f32,
        dy: 1.0f32,
    },
    DecorSegment {
        sprite_id: 458816,
        dx: 20.0f32,
        dy: -16.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 14.0f32,
        dy: 1.0f32,
    },
];

pub const DECOR_METHOD_LOWER_AA: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458815,
        dx: -10.0f32,
        dy: -15.0f32,
    },
    DecorSegment {
        sprite_id: 458816,
        dx: 18.0f32,
        dy: -21.0f32,
    },
    DecorSegment {
        sprite_id: 458815,
        dx: -1.0f32,
        dy: -14.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 23.0f32,
        dy: -40.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: -7.0f32,
        dy: 1.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 7.0f32,
        dy: -19.0f32,
    },
    DecorSegment {
        sprite_id: 458813,
        dx: 16.0f32,
        dy: -70.0f32,
    },
    DecorSegment {
        sprite_id: 458812,
        dx: -3.0f32,
        dy: -46.0f32,
    },
];

pub const DECOR_METHOD_LOWER_AB: &[DecorSegment] = &[
    DecorSegment {
        sprite_id: 458815,
        dx: -14.0f32,
        dy: -54.0f32,
    },
    DecorSegment {
        sprite_id: 458816,
        dx: 9.0f32,
        dy: -33.0f32,
    },
    DecorSegment {
        sprite_id: 458815,
        dx: 15.0f32,
        dy: -13.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 6.0f32,
        dy: -2.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: 16.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458817,
        dx: -17.0f32,
        dy: -44.0f32,
    },
    DecorSegment {
        sprite_id: 458813,
        dx: -6.0f32,
        dy: -29.0f32,
    },
    DecorSegment {
        sprite_id: 458812,
        dx: 0.0f32,
        dy: -60.0f32,
    },
];

pub fn get_composite_decor(did: u8, stage: u8) -> Option<&'static [DecorSegment]> {
    match did {
        18 => match stage {
            0 => Some(DECOR_METHOD_LOWER_A),
            1 => Some(DECOR_METHOD_LOWER_B),
            2 => Some(DECOR_METHOD_LOWER_C),
            3 => Some(DECOR_METHOD_LOWER_D),
            4 => Some(DECOR_METHOD_LOWER_E),
            5 => Some(DECOR_METHOD_LOWER_F),
            6 => Some(DECOR_METHOD_LOWER_G),
            7 => Some(DECOR_METHOD_LOWER_H),
            8 => Some(DECOR_METHOD_LOWER_I),
            9 => Some(DECOR_METHOD_LOWER_J),
            10 => Some(DECOR_METHOD_LOWER_K),
            11 => Some(DECOR_METHOD_LOWER_L),
            12 => Some(DECOR_METHOD_LOWER_M),
            _ => None,
        },
        1 => match stage {
            0 => Some(DECOR_METHOD_LOWER_N),
            1 => Some(DECOR_METHOD_LOWER_O),
            2 => Some(DECOR_METHOD_LOWER_P),
            3 => Some(DECOR_METHOD_LOWER_Q),
            4 => Some(DECOR_METHOD_LOWER_R),
            5 => Some(DECOR_METHOD_LOWER_S),
            6 => Some(DECOR_METHOD_LOWER_T),
            7 => Some(DECOR_METHOD_LOWER_U),
            _ => None,
        },
        5 => match stage {
            0 => Some(DECOR_METHOD_LOWER_V),
            1 => Some(DECOR_METHOD_LOWER_W),
            2 => Some(DECOR_METHOD_LOWER_X),
            3 => Some(DECOR_METHOD_LOWER_Y),
            4 => Some(DECOR_METHOD_LOWER_Z),
            5 => Some(DECOR_METHOD_UPPER_A),
            6 => Some(DECOR_METHOD_UPPER_B),
            7 => Some(DECOR_METHOD_UPPER_C),
            8 => Some(DECOR_METHOD_UPPER_D),
            _ => None,
        },
        13 => match stage {
            0 => Some(DECOR_METHOD_UPPER_E),
            1 => Some(DECOR_METHOD_UPPER_F),
            2 => Some(DECOR_METHOD_UPPER_G),
            3 => Some(DECOR_METHOD_UPPER_H),
            4 => Some(DECOR_METHOD_UPPER_I),
            5 => Some(DECOR_METHOD_UPPER_J),
            6 => Some(DECOR_METHOD_UPPER_K),
            7 => Some(DECOR_METHOD_UPPER_L),
            8 => Some(DECOR_METHOD_UPPER_M),
            9 => Some(DECOR_METHOD_UPPER_N),
            10 => Some(DECOR_METHOD_UPPER_O),
            11 => Some(DECOR_METHOD_UPPER_P),
            _ => None,
        },
        21 => match stage {
            0 => Some(DECOR_METHOD_UPPER_Q),
            1 => Some(DECOR_METHOD_UPPER_R),
            2 => Some(DECOR_METHOD_UPPER_S),
            3 => Some(DECOR_METHOD_UPPER_T),
            _ => None,
        },
        22 => match stage {
            0 => Some(DECOR_METHOD_UPPER_U),
            1 => Some(DECOR_METHOD_UPPER_V),
            2 => Some(DECOR_METHOD_UPPER_V),
            3 => Some(DECOR_METHOD_UPPER_V),
            _ => None,
        },
        49 => match stage {
            0 => Some(DECOR_METHOD_UPPER_W),
            1 => Some(DECOR_METHOD_UPPER_X),
            2 => Some(DECOR_METHOD_UPPER_Y),
            3 => Some(DECOR_METHOD_UPPER_Z),
            4 => Some(DECOR_METHOD_LOWER_AA),
            5 => Some(DECOR_METHOD_LOWER_AB),
            _ => None,
        },
        _ => None,
    }
}
